### ISSUE TITLE
Kernel modules must get installed in a reasonable place

### ISSUE THREAD

**Issue by eddywestbrook** [freenet/contrib#8]
I'm not sure how to write my CMake scripts to make this happen, nor where this reasonable place is.

**Comment by Thynix** [comment]
I wasn't aware that contrib includes kernel modules. Where is that?

**Comment by eddywestbrook** [comment]
Whoops! I'm so sorry, I must have posted that on the wrong github project! I was wondering why it never showed up...

Eddy

**Comment by Thynix** [comment]
Okay, that makes more sense.
